default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV["DATABASE_URL"] %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default

# Para evitar o erro com `cable`, adicione esta configuração:
cable:
  <<: *default
  database: cable_production # Você pode especificar outro nome se preferir.
